1 - ERROR DE SIMBOLO - #include
1 - OP.RELACIONAL - <
1 - IDENTIFICADOR MAL FORMADO - stdio.h
1 - OP.RELACIONAL - >
3 - RESERVADA - int
3 - RESERVADA - main
3 - DELIMITADOR - (
3 - DELIMITADOR - )
3 - DELIMITADOR - {
5 - RESERVADA - int
5 - IDENTIFICADOR - x
5 - DELIMITADOR - ,
5 - IDENTIFICADOR - y
5 - DELIMITADOR - ,
5 - IDENTIFICADOR - w
5 - DELIMITADOR - ,
5 - IDENTIFICADOR - z
5 - DELIMITADOR - ;
6 - IDENTIFICADOR - x
6 - OP.RELACIONAL - =
6 - NUMERO - 12
6 - NUMERO - -2
6 - DELIMITADOR - ;
7 - IDENTIFICADOR - x
7 - OP.RELACIONAL - =
7 - NUMERO - 12
7 - OP.ARITMETICO - +
7 - NUMERO - 2
8 - IDENTIFICADOR - x
8 - OP.RELACIONAL - =
8 - NUMERO - 3
8 - OP.ARITMETICO - -
8 - NUMERO - -4
9 - IDENTIFICADOR - a
9 - OP.RELACIONAL - =
9 - NUMERAL MAL FORMADO - -3#
9 - DELIMITADOR - ;
9 - STRING - ""
10 - NUMERAL MAL FORMADO - -2#
11 - ERROR DE SIMBOLO - .12
12 - RESERVADA - print
12 - DELIMITADOR - (
12 - STRING - "Vitoria %d x %d Bahia"
12 - IDENTIFICADOR - x
12 - DELIMITADOR - ,
12 - IDENTIFICADOR - y
12 - DELIMITADOR - )
12 - DELIMITADOR - ;
13 - RESERVADA - scan
13 - DELIMITADOR - (
13 - STRING - "%d"
13 - DELIMITADOR - ,
13 - ERROR DE SIMBOLO - &x
13 - DELIMITADOR - )
13 - DELIMITADOR - ;
16 - STRING MAL FORMADA - "abc && 23
17 - STRING MAL FORMADA - "\"
18 - STRING - "\"\"\"\""
19 - STRING MAL FORMADA - "
20 - STRING - ""
20 - STRING MAL FORMADA - "
21 - STRING - "abc"
21 - STRING - "abc2"
22 - RESERVADA - scan
22 - DELIMITADOR - (
22 - STRING - "%d"
22 - DELIMITADOR - ,
22 - ERROR DE SIMBOLO - &y
22 - DELIMITADOR - )
22 - DELIMITADOR - ;
26 - RESERVADA - print
26 - DELIMITADOR - (
26 - STRING - "Juazeirense "
26 - DELIMITADOR - ,
26 - IDENTIFICADOR - z
26 - DELIMITADOR - )
26 - DELIMITADOR - ;
27 - RESERVADA - scan
27 - DELIMITADOR - (
27 - STRING - "%d"
27 - DELIMITADOR - ,
27 - ERROR DE SIMBOLO - &z
27 - DELIMITADOR - )
27 - DELIMITADOR - ;
29 - RESERVADA - scan
29 - DELIMITADOR - ;
30 - IDENTIFICADOR - get
30 - DELIMITADOR - (
30 - DELIMITADOR - )
30 - DELIMITADOR - ;
